services:
  app:
    build: .
    container_name: rentx
    environment:
      - DATABASE_HOST=database
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres
    container_name: rentx_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
